# Generated by Django 4.2.6 on 2023-10-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("discount", models.PositiveSmallIntegerField()),
                ("stock", models.PositiveIntegerField()),
                (
                    "image_url",
                    models.URLField(
                        blank=True, default="https://picsum.photos/256", max_length=2047
                    ),
                ),
            ],
        ),
    ]
